In [1]:
import pandas as pd


calendar = pd.read_csv('calendar.csv')
inventory = pd.read_csv('inventory.csv')

In [8]:
calendar

,date,holiday_name,holiday,shops_closed,winter_school_holidays,school_holidays,warehouse
0,2022-03-16,week,0,0,0,0,Frankfurt_1
1,2020-03-22,week,0,0,0,0,Frankfurt_1
2,2018-02-07,week,0,0,0,0,Frankfurt_1
3,2018-08-10,week,0,0,0,0,Frankfurt_1
4,2017-10-26,week,0,0,0,0,Prague_2
...,...,...,...,...,...,...,...
23011,2019-04-20,week,1,0,0,0,Munich_1
23012,2018-03-31,week,1,0,0,0,Munich_1
23013,2017-04-15,week,1,0,0,0,Munich_1
23014,2023-04-08,week,1,0,0,1,Munich_1
23015,2024-03-30,week,1,0,0,1,Munich_1

In [7]:
calendar['holiday_name'].value_counts()

holiday_name
week                                                           22086
Labour Day                                                        63
2nd Christmas Day                                                 63
1st Christmas Day                                                 63
International womens day                                          63
Christmas Eve                                                     63
New Years Day                                                     63
Good Friday                                                       42
Easter Monday                                                     42
Den boje za svobodu a demokracii                                  36
Den vzniku samostatneho ceskoslovenskeho statu                    36
Jan Hus                                                           36
Den ceske statnosti                                               36
Den osvobozeni                                                    36
Cyrila a Metodej                                                  36
Whit sunday                                                       27
Whit monday                                                       27
Memorial Day for the Victims of the Holocaust                     18
All Saints Day                                                    18
Ascension day                                                     18
Corpus Christi                                                    18
German Unity Day                                                  18
Memorial Day of the Republic                                       9
State Foundation Day                                               9
Independent Hungary Day                                            9
Memorial Day for the Martyrs of Arad                               9
Memorial day of the 1956 Revolution                                9
Memorial Day for the Victims of the Communist Dictatorships        9
Epiphany                                                           9
Assumption of the Virgin Mary                                      9
Reformation Day                                                    9
National Defense Day                                               8
Day of National Unity                                              8
Peace Festival in Augsburg                                         6
Hungary National Day Holiday                                       2
Christmas Holiday                                                  1
1848 Revolution Memorial Day (Extra holiday)                       1
All Saints' Day Holiday                                            1
Name: count, dtype: int64

In [6]:
calendar['holiday_name'].fillna('week', inplace=True)